config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :video_requests do
    member do
      resources :comments
    end
  end

  resources :channels
  namespace :static_pages do
    get :about
  end
  root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :user
  has_many :video_requests
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :channels
  has_many :comments, class_name: 'VideoRequest::Comment'
end

app/models/video_request.rb
class VideoRequest < ApplicationRecord
  belongs_to :channel
  has_many :comments
end

app/models/video_request/comment.rb
class VideoRequest::Comment < ApplicationRecord
  belongs_to :video_request
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_filter :set_channel, only: [:show]

  before_filter only: [:create, :update] do
    redirect_to(root_path) unless user_signed_in?
  end

  def index
    @channels = Channel.all
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(channel_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  def show; end

  private

  def set_channel
    @channel = Channel.find(params[:id])
  end

  def channel_params
    params.require(:channel).permit(:name, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_video_request_comment, only: [:show, :edit, :update, :destroy]

  # GET /video_request_comments
  # GET /video_request_comments.json
  def index
    @video_request_comments = VideoRequest::Comment.all
  end

  # GET /video_request_comments/1
  # GET /video_request_comments/1.json
  def show
  end

  # GET /video_request_comments/new
  def new
    @video_request_comment = VideoRequest::Comment.new
  end

  # GET /video_request_comments/1/edit
  def edit
  end

  # POST /video_request_comments
  # POST /video_request_comments.json
  def create
    @video_request_comment = VideoRequest::Comment.new(
      video_request_comment_params.merge(video_request_id: params['id'], user_id: current_user.id)
    )
    respond_to do |format|
      if @video_request_comment.save
        format.html { redirect_back(fallback_location: root_path) }
        format.json { render :show, status: :created, location: @video_request_comment }
      else
        format.html { render :new }
        format.json { render json: @video_request_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /video_request_comments/1
  # PATCH/PUT /video_request_comments/1.json
  def update
    respond_to do |format|
      if @video_request_comment.update(video_request_comment_params)
        format.html { redirect_to @video_request_comment, notice: 'Video request comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @video_request_comment }
      else
        format.html { render :edit }
        format.json { render json: @video_request_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_request_comments/1
  # DELETE /video_request_comments/1.json
  def destroy
    @video_request_comment.destroy
    respond_to do |format|
      format.html { redirect_to video_request_comments_url, notice: 'Video request comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_request_comment
      @video_request_comment = VideoRequestComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_request_comment_params
      params.require(:video_request_comment).permit(:value)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @video_requests = VideoRequest.order('created_at DESC')
  end

  def about
  end
end

app/controllers/video_requests_controller.rb
class VideoRequestsController < ApplicationController
  before_action :set_video_request, only: [:show, :edit, :update, :destroy]

  before_filter only: [:create, :update] do
    redirect_to(root_path) unless user_signed_in?
  end

  # GET /video_requests
  # GET /video_requests.json
  def index
    @video_requests = VideoRequest.all
  end

  # GET /video_requests/1
  # GET /video_requests/1.json
  def show; end

  # GET /video_requests/new
  def new
    @video_request = VideoRequest.new
  end

  # GET /video_requests/1/edit
  def edit; end

  # POST /video_requests
  # POST /video_requests.json
  def create
    @video_request = VideoRequest.new(video_request_params)
    respond_to do |format|
      if @video_request.save
        format.html { redirect_to @video_request, notice: 'Video request was successfully created.' }
        format.json { render :show, status: :created, location: @video_request }
      else
        format.html { render :new }
        format.json { render json: @video_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /video_requests/1
  # PATCH/PUT /video_requests/1.json
  def update
    respond_to do |format|
      if @video_request.update(video_request_params)
        format.html { redirect_to @video_request, notice: 'Video request was successfully updated.' }
        format.json { render :show, status: :ok, location: @video_request }
      else
        format.html { render :edit }
        format.json { render json: @video_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_requests/1
  # DELETE /video_requests/1.json
  def destroy
    @video_request.destroy
    respond_to do |format|
      format.html { redirect_to video_requests_url, notice: 'Video request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_request
      @video_request = VideoRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_request_params
      params.require(:video_request).permit(:title, :description, :slots, :channel_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/video_requests_helper.rb
module VideoRequestsHelper
end

app/views/channels/_form.html.erb
<%= form_for(channel) do |f| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name, class: 'channel-field' %>
  <%= f.text_field :name %>

  <%= f.label :description, class: "channel-field" %>
  <%= f.text_area :description %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Channel</h1>

<table class="video-requests-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.name %></td>
        <td><%= channel.description %></td>
        <td><%= link_to 'Show', channel %></td>
        <% if user_signed_in? && current_user.id == channel.user_id %>
          <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
          <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New channel', new_channel_path %>

app/views/channels/new.html.erb
<h1 class='page-title channel-title'>New channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @channel.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @channel.description %>
</p>

<% if user_signed_in? && current_user.id == @channel.user_id %>
  <%= link_to 'Edit', edit_channel_path(@channel) %> |
<% end %>
<%= link_to 'Back', channels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Talent Meet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', href: 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css', crossorigin: 'anonymous', integrity: 'sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u' %>
  </head>

  <body class="page-background">
    <nav class='navbar navbar-inverse'>
    <div class="container-fluid">
      <div class="navbar-header">
        <img alt="Brand" src="https://image.ibb.co/d5nJfk/oie_Reiqzmsz_Fnv_G.png">
      </div>
      <div class='container-fluid'>
        <%= link_to 'Home', root_path, role: 'button', class: 'btn btn-inverse navbar-link' %>
        <%= link_to 'Video Requests', video_requests_path, role: 'button', class: 'btn btn-inverse navbar-link' %>
        <%= link_to 'Channels', channels_path, role: 'button', class: 'btn btn-inverse navbar-link' %>
        <%= link_to 'About', static_pages_about_path, role: 'button', class: 'btn btn-inverse navbar-link' %>
        <% if user_signed_in? %>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, role: 'button', class: 'btn btn-inverse navbar-link' %>
        <% else %>
          <%= link_to 'Sign In', new_user_session_path, role: 'button', class: 'btn btn-inverse navbar-link' %>
        <% end %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>



app/views/static_pages/about.html.erb
<a class="logo" href="#">
  <img alt="Logo" src="https://s23.postimg.org/z1e6va0l7/oie_Ep_Jz_Lp_Ep_Bqf1.png">
</a>

<h1 class="page-title about-us-title">About Us</h1>
<p class="about-us-text">
  Welcome to Talent Meet so alittle about us is i always notice how when it came to youtube commuinity people always ask people for help on social media thats they need someone to help them make a new video may it be acting or just voice there people out there so i wanted to end that search and make a site dedicated to anyone who needs help can finnaly have people ready to help our site is simnple but still developing just add your channel and ask for a video request when your sign in its that simple anyways thanks for being intrested on our site -sincerely Talent Meet Dev Team.
</p>

app/views/static_pages/index.html.erb
<p id="notice"><%= notice %></p>
<a class="logo" href="#">
  <img class alt="Logo" src="https://s23.postimg.org/z1e6va0l7/oie_Ep_Jz_Lp_Ep_Bqf1.png">
</a>
<div class='container'>
  <h1 class='page-title'>Video Requests</h1>
  <div class='col-md-12'>
    <% @video_requests.each do |video_request| %>
      <%= render 'video_requests/list_item', video_request: video_request %>
    <% end %>
  </div>
</div>

app/views/video_request_comments/_form.html.erb
<%= form_for(video_request_comment) do |f| %>
  <% if video_request_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video_request_comment.errors.count, "error") %> prohibited this video_request_comment from being saved:</h2>

      <ul>
      <% video_request_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/video_request_comments/edit.html.erb
<h1>Editing Video Request Comment</h1>

<%= render 'form', video_request_comment: @video_request_comment %>

<%= link_to 'Show', @video_request_comment %> |
<%= link_to 'Back', video_request_comments_path %>

app/views/video_request_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Video Request Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @video_request_comments.each do |video_request_comment| %>
      <tr>
        <td><%= link_to 'Show', video_request_comment %></td>
        <td><%= link_to 'Edit', edit_video_request_comment_path(video_request_comment) %></td>
        <td><%= link_to 'Destroy', video_request_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video Request Comment', new_video_request_comment_path %>

app/views/video_request_comments/new.html.erb
<h1>New Video Request Comment</h1>

<%= render 'form', video_request_comment: @video_request_comment %>

<%= link_to 'Back', video_request_comments_path %>

app/views/video_request_comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_video_request_comment_path(@video_request_comment) %> |
<%= link_to 'Back', video_request_comments_path %>

app/views/video_requests/_comment.html.erb
<p> food </p>

app/views/video_requests/_comment_list.html.erb
<% video_request.comments.each do |comment| %>
  <p>
    <%= comment.user.email %>
    <%= comment.value %>
  </p>
<% end %>
<% if user_signed_in? %>
  <%= form_for VideoRequest::Comment.new, url: comments_path(video_request.id) do |f| %>
    <%= f.text_field :value %>
    <%= f.submit 'Post' %>
  <% end %>
<% end %>

app/views/video_requests/_form.html.erb
<%= form_for(video_request) do |f| %>
  <% if video_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video_request.errors.count, "error") %> prohibited this video_request from being saved:</h2>

      <ul>
      <% video_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :channel_id %>
    <%= f.select :channel_id, current_user.channels.map { |channel| [channel.name, channel.id] } %>
  </div>

  <div class="field">
    <%= f.label :slots %>
    <%= f.number_field :slots %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/video_requests/_list_item.html.erb
<div class='homepage-video-request-item'>
  <span> <%= pluralize(video_request.slots, 'Slot') %> Left </span>
  <span class='homepage-video-request-item__description'><%= video_request.description %></span>
  <p> Requested By: <%= video_request.channel.name %></p>
  <%= render 'video_requests/comment_list', video_request: video_request %>

</div>

app/views/video_requests/edit.html.erb
<h1>Editing Video Request</h1>

<%= render 'form', video_request: @video_request %>

<%= link_to 'Show', @video_request %> |
<%= link_to 'Back', video_requests_path %>

app/views/video_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Video Requests</h1>

<table class="video-requests-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Slots</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @video_requests.each do |video_request| %>
      <tr>
        <td><%= video_request.title %></td>
        <td><%= link_to video_request.description, video_request %></td>
        <td><%= link_to video_request.slots, video_request %></td>
        <% if user_signed_in? && current_user.id == video_request.channel.user_id %>
          <td><%= link_to 'Edit', edit_video_request_path(video_request) %></td>
          <td><%= link_to 'Destroy', video_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>

  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Video Request', new_video_request_path %>
<% end %>

app/views/video_requests/new.html.erb
<h1>New Video Request</h1>

<%= render 'form', video_request: @video_request %>

<%= link_to 'Back', video_requests_path %>


app/views/video_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video_request.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video_request.description %>
</p>

<p>
  <strong>Slots:</strong>
  <%= @video_request.slots %>
</p>
<% if user_signed_in? && current_user.id == @video_request.channel.user_id %>
  <%= link_to 'Edit', edit_video_request_path(@video_request) %> |
<% end %>
<%= link_to 'Back', video_requests_path %>
